--- 
- name: installing apache  # IT IS THE PLAY.
  hosts: all               # WE ARE SAYING THE LIST OF NODES. WHERE WE WANT TO RUN.FOR NOW WE ARE GIVING ALL.
  become: yes              # RUNNING ALL THE COMMANDS IN SUDO USERS."sudo" MEANS ADMINSTRATIVE ACESS.
  tasks:
    - name: install apache2    # IT'S A PLAY.HERE, WE HAVE TO WRITE WHAT WE WANT TO DO
      ansible.builtin.apt:     # IT IS A MODULE FOR THE "apt" PACKAGE MANAGER.
        name: apache2
        update_cache: yes      # IT IS LIKE "sudo apt update". "apt" IS PACKEGE MANAGER FOR "UBUNTU OPERATING SYSTEM"
        state: present         # WHETHER WE GIVE "state" OR NOT. THE DEFAULT STATE IS PRESENT.


# --> Here, I am Writeing Ansible Palybook for Apache.
# --> Apache is a webserver.
# --> Playbook is a collection of tasks.
# --> In ansible work is done by Modules.

### MANUAL STEPS FOR APACHE ###

# --> sudo apt update               - "apt" is package manager for ubuntu. It updates the package definitions.(Advanced Package Tool(APT))
# --> sudo apt install apache2 -y .
# --> sudo systemctl status nginx   - checking the status whether it is in running state or not.